In [1]:
import sys
import os
sys.path.append(os.getcwd())

In [2]:
import kNN

In [3]:
group,labels = kNN.createDataSet()

In [6]:
group

array([[ 1. ,  1.1],
       [ 1. ,  1. ],
       [ 0. ,  0. ],
       [ 0. ,  0.1]])

In [7]:
labels

['A', 'A', 'B', 'B']

In [8]:
kNN.classify0([0,0], group, labels, 3)

'B'

In [9]:
from numpy import *
import operator
from os import listdir

In [10]:
tile([0,0],(4,1))-group

array([[-1. , -1.1],
       [-1. , -1. ],
       [ 0. ,  0. ],
       [ 0. , -0.1]])

分析步骤
```
diffMat = tile(inX, (dataSetSize,1)) - dataSet
```
1.统计测试集有几个数据
2.调用tile函数将未知点数据inX拷贝出与测试集数据的个数一样
3.然后将未知点数据与测试集数据相减.也就是x1-x2,y1-y2
4.然后就是运用欧几里得公式求点与点之间的距离

In [11]:
def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    diffMat = tile(inX, (dataSetSize,1)) - dataSet
    sqDiffMat = diffMat**2
    sqDistances = sqDiffMat.sum(axis=1)
    distances = sqDistances**0.5
    sortedDistIndicies = distances.argsort()     
    classCount={}          
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    sortedClassCount = sorted(classCount.iteritems(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]

In [12]:
classify0([0,0], group, labels, 3)

'B'

## 在约会网站上使用K近邻算法

准备数据:从文本文件中解析数据

In [13]:
!tail datingTestSet2.txt

In [14]:
def file2matrix(filename):
    fr=open(filename)
    arrayOlines=fr.readlines()
    # 得到文件行数
    numberOfLines=len(arrayOlines)
    # zero函数,创建和文件一样行数以及3列的矩阵,元素都为0
    returnMat=zeros((numberOfLines,3))
    classLabelVector=[]
    index=0
    for line in arrayOlines:
        line=line.strip()
        # 将每一行的元素写入到一个list中
        listFromLine=line.split('\t')
        # 第四列是标签,取出前3列的特征元素
        returnMat[index,:]=listFromLine[0:3]
        # 把最后一列的标签元素追加到标签集合中
        classLabelVector.append(int(listFromLine[-1]))
        index+=1
    return returnMat,classLabelVector

In [15]:
returnMat,classLabelVector=file2matrix("datingTestSet2.txt")

In [16]:
returnMat

array([[  4.09200000e+04,   8.32697600e+00,   9.53952000e-01],
       [  1.44880000e+04,   7.15346900e+00,   1.67390400e+00],
       [  2.60520000e+04,   1.44187100e+00,   8.05124000e-01],
       ..., 
       [  2.65750000e+04,   1.06501020e+01,   8.66627000e-01],
       [  4.81110000e+04,   9.13452800e+00,   7.28045000e-01],
       [  4.37570000e+04,   7.88260100e+00,   1.33244600e+00]])