In [1]:
import numpy as np

In [ ]:
a=np.array([0,1,2])

`tile`函数解释:<br>
numpy.tile(A, reps)
+ A : array_like
    + The input array.(输入的数组)
+ reps : array_like
    + The number of repetitions of A along each axis.(把A在每个轴上重复对应的次数)

`2`表示:<br>
在列的方向上重复a两次

In [3]:
np.tile(a,2)

array([0, 1, 2, 0, 1, 2])

`(2,3)`表示:<br>在行的方向上重复a2次,在列的方向上重复a3次

In [4]:
np.tile(a,(2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [5]:
np.tile(a,(2,1,2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [6]:
np.tile(a,(2,2,1))

array([[[0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [8]:
# zeros函数
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])